verify_email:
  path: /verify-email
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  permanent: true
  keepQueryParams: true

profile:
  path: /profile
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  permanent: true
  keepQueryParams: true
  
reset_password:
  path: /reset-password/reset/{token}
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  permanent: true
  keepQueryParams: true